#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EmaXamarin.Droid.Resource", IsApplication=true)]

namespace EmaXamarin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::EmaXamarin.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::EmaXamarin.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_clear_playlist = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_manage = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_preferences = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_search = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_upload = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
